import time
import os
import random, os, sys, math, json
from time import sleep
import time
def clear(t):
  time.sleep(t)
def p(t):
  print(t)
def clear():
  os.system('clear')
def write(words):
  for char in words:
    sleep(0.05)
    sys.stdout.write(char)
    sys.stdout.flush()
clear()
write("These are the credits....")
print("")
write("Loading......")
clear()
#write("Press enter > ")
print("")
print('''Game by: 
┏━━━┳┓╋╋╋┏┓
┃┏━┓┃┃╋╋╋┃┃
┃┃╋┃┃┃┏━━┫┗━┳━━┳━┳┓┏┳┓┏┳━━┳━┳┳━━┓
┃┗━┛┃┃┃┏┓┃┏┓┃┏┓┃┏┫┃┃┃┗┛┃┃━┫┏╋┫┏━┛
┃┏━┓┃┗┫┗┛┃┃┃┃┏┓┃┃┃┗┛┃┃┃┃┃━┫┃┃┃┗━┓
┗┛╋┗┻━┫┏━┻┛┗┻┛┗┻┛┗━━┻┻┻┻━━┻┛┗┻━━┛
╋╋╋╋╋╋┃┃
╋╋╋╋╋╋┗┛''')
time.sleep(1)
print("")
write("With the help of:")
time.sleep(1)
print("")
print('''┏━━━━┳┓╋╋╋╋╋┏━━━┳━━━┳━━━┓
┃┏┓┏┓┃┃╋╋╋╋╋┃┏━━┫┏━┓┃┏━┓┃
┗┛┃┃┗┫┗━┳━━┓┃┗━━┫┃╋┃┃┃╋┃┃
╋╋┃┃╋┃┏┓┃┃━┫┃┏━━┫┗━┛┃┗━┛┃
╋╋┃┃╋┃┃┃┃┃━┫┃┃╋╋┃┏━┓┃┏━┓┃
╋╋┗┛╋┗┛┗┻━━┛┗┛╋╋┗┛╋┗┻┛╋┗┛''')
print("")
write("Aka:")
time.sleep(1)
print("")
print('''┏━━━━┓╋╋╋╋╋╋╋╋╋╋╋╋╋┏┓
┗━━┓━┃╋╋╋╋╋╋╋╋╋╋╋╋╋┃┃
╋╋┏┛┏╋┓╋┏┳━━┳━┳━━┳━┛┣━━┓
╋┏┛┏┛┃┃╋┃┃┏┓┃┏┫┏┓┃┏┓┃┃━┫
┏┛━┗━┫┗━┛┃┗┛┃┃┃┏┓┃┗┛┃┃━┫
┗━━━━┻━┓┏┻━┓┣┛┗┛┗┻━━┻━━┛
╋╋╋╋╋┏━┛┃┏━┛┃
╋╋╋╋╋┗━━┛┗━━┛''')
print("")
write("And..")
print("")
time.sleep((1))
print('''┏━┓╋╋╋╋╋╋╋╋╋╋┏┳┓┏┓
┃┏╋━┳┓┏━┳┳┳━┳┛┃┗┛┣┳┳━┓
┃┗┫╋┃┗┫╋┃┏┫┻┫╋┃┏┓┃┃┃┻┫
┗━┻━┻━┻━┻┛┗━┻━┻┛┗┻━┻━┛''')
time.sleep(1)
print("")
#print("and")
#print(e.read())
enter = input("[ENTER] > ")
clear()
print("*Warning*")
time.sleep(0.5)
write("Gramatical mistakes can lead to big problems")
time.sleep(1)
write("Btw please dont use Yeah, or yeah to answer anything unless its the first question ")
print("If it stops going that means you lost, because it makes the time sleep for Infinite...")
time.sleep(1.5)
print("\n"*4)
print("You call a taxi..")
time.sleep(1)
option109 = input("Do you want to enter the taxi to go to the airport? :    ")
if option109 in ("1","One","one","Yes.","yes.","ye.","Ye.","Yes","yes","ye","Ye","Yeah","yeah","yeah.","Yeah.","y","Y","Sure.","Sure","sure","sure."):time.sleep(1), print("You enter the taxi.."), time.sleep(1),
else: time.sleep(1), input("Why? : "),time.sleep(1), print("Sike I dont actually care."), time.sleep(1), print("BADDIE"),time.sleep(1), print("But you descide to go home.."),time.sleep(1), print("And live the rest of your life in your home"), time.sleep(1), print("Wait..."),time.sleep(1), print("You dont have a home.."),time.sleep(1), print("XDXDXDDXDXDXD"), time.sleep(1), print("JK JK"), time.sleep(1), print("This is all meant as a funy joke"), print("Any, /e timestop inf"),time.sleep(1000000000)
time.sleep(1)
print("You ask him to take you to the airport.")
time.sleep(1)
print("You are now at the airport..")
time.sleep(1)
print("You throught security and walk to the airplane..")
time.sleep(1)
print("Your now at the airplane!")
time.sleep(1)
print("But the real question is...")
time.sleep(1)
print("")
airplane1question = input("Do you want to go in the airplane?  :  ")
print("")
time.sleep(0.5)
if airplane1question in ("1","One","one","Yes.","yes.","ye.","Ye.","Yes","yes","ye","Ye","Yeah","yeah","yeah.","Yeah.","y","Y","Sure.","Sure","sure","sure."): print("You enter the airplane")
else:time.sleep(1),print("You get fired by United airlines."),time.sleep(1),print("never get to fly a plane again."),time.sleep(1000000000)
time.sleep(0.9)
print("You are now in the cockpit of a United 777-200 with 286 souls onboard including yourself...")
time.sleep(0.6)
print("")
print("You have the options to...")
time.sleep(1)
two = print("1: Contact the Air Traffic Control(ATC).")
time.sleep(0.8)
ne = print("2: Taxi and take off.")
time.sleep(1)
option1 = input("Which do you choose?  :  ")
if option1 in("1","One","one.","One.","one"):print("You contact the Air Traffic Control.")
else: print("You proceeded to take off"), time.sleep(1), print("As soon as you take off your plane malfunctions and hits a Delta airbus A320 with 163 souls onboard..."), time.sleep(0.7), print("Ultimately leading to your death and 448 others..."), time.sleep(0.9),print("Your funeral is held at, Wendys, specificly, Sir this is a wendys."),time.sleep(0.5),print("R.I.P"), time.sleep(10000000)
time.sleep(1)
print("They tell you to wait since two other planes were coming")
time.sleep(0.7)
print("")
print("Your First officer (Co-pilot) says that was a close one*")
time.sleep(1)
print("You have the choice to say two things...")
time.sleep(0.6)
onee = print("1: No it wasnt!")
twoo = print("2: Indeed it was.")
option2 = input("Which do you choose?  :  ")
if option2 in ("2","Two","two","two.","Two."):time.sleep(1), print("You both agreed.")
else: print("You were on speaker mode causing everyone to fight"), time.sleep(0.5), print("You win against your co-pilot in a fist fight"),time.sleep(0.7), print("Unfortunately that cannot be said for the rest of your passenger."),time.sleep(0.5), print("You die"), time.sleep(0.9),print("Your funeral is held at a Pokémon game...hmmmmm..."),print("SilverPrism takes you to your grave"), time.sleep(100000000)
time.sleep(0.5)
print("You call the command tower again...")
time.sleep(1)
print("They tell you it's safe to go")
time.sleep(0.5)
print("")
print("You have two options..")
time.sleep(0.5)
one2 = print("1: Taxi to the runway, set flaps, push to full throttle, and take off.")
time.sleep(0.5)
two2 = print("2: You stay.")
option2 = input("Which do you do? :   ")
if option2 in ("1","One","one","One.","one."): time.sleep(1),print("You took off safley")
else: time.sleep(0.5),print("You dont take off"), time.sleep(0.5), print("You are told once again to take off"),time.sleep(0.2), print("You are told two more times.."),time.sleep(1.2), print("The police come into the cockpit and take you to the mental hospital"), time.sleep(1),print("You never see an airplane again..."), time.sleep(10000000)
time.sleep(1)
print("You are now in the air.")
time.sleep(0.5)
print("Your getting tired, you have two options")
time.sleep(1)
one3 = print("1: Turn on autopilot")
time.sleep(0.5)
three1 = print("2: You tell your First officer (Co-pilo) to pilot")
option3 = input("Which do you choose?  :  ")
if option3 in ("1","One","one","one.","One."): print("You turn on your autopilot"), time.sleep(1), print("It was very smooth.."), time.sleep(1), print("Until.."), time.sleep(0.5), print("You realise THERE HAS BEEN A MAFUNCTION AND YOU CRASHED!!!"), time.sleep(0.5), print("Your funeral is held at Burger King"),time.sleep(0.5),print("lol..."), time.sleep(1000000000)
else: print("You give the steer to your co-pilot")
time.sleep(1)
print("")
print("You wake up after a suprisingly smooth flight operated by your co-pilot")
time.sleep(0.5)
print("You forgot where your going to so you ask your co-pilot")
time.sleep(0.5)
print("")
print("He tells you your going to Texas")
time.sleep(0.5)
print("You have two options...")
time.sleep(0.5)
one4 = print("1: Ingage in small talk.")
two4 = print("2: You keep flying")
option5 = input("What do you do?  :  ")
if option5 in ("1","One.","one.","one","One"): time.sleep(1),print("You befreind him"), print("It turns out his name is Eric, but he calls himself IcemasterEric")

else: print("You keep flying..")
print("")
time.sleep(1)
print("....................")
time.sleep(0.5)
print("Everything is normal.")
time.sleep(1)
print("Until...")
time.sleep(1)
print("You see a red light...")
time.sleep(1)
print("What do you do?")
time.sleep(0.5)
one5 = print("1: Panic.")
two5 = print("2: Stay calm, and warn your First officer (Co-pilot) and crew that theres a malfunction")
option6 = input("What do you pick?  :  ")
if option6 in ("2","Two","two","two.","Two."): time.sleep(1),print("You warn your associates and survive the incident")
else: time.sleep(1), print("You panic and everyone onboard dies"), print("Your funeral was held at Mario jump"), time.sleep(100000000)
print("")
time.sleep(1)
print("Your almost at texas")
time.sleep(1)
print("But two jets come and start shooting at you...")
time.sleep(1)
print("You get a signal that two people named, aboutabot, and Joshsan are operating it ")
time.sleep(1)

print("What do you do?")
print("1: Do a barrel roll")
print("2: Nothing..")
option7 = input("WHAT DO YOU DO!!!!??  :  ")
if option7 in ("1","One","one","One.","one."): time.sleep(1),print("You did a barrel roll, and exploded both jets"), time.sleep(1),print("But one half of your passengers died"), print("and both your wings are broken...")
else: time.sleep(1), print("You get shot down by the jets, 3/4th of your passengers are killed"),time.sleep(1), print("Eric, your co-pilot, survives also")
print("")
time.sleep(1)
print("There are only 3 parachutes, but Michel Jackson took one of them")

time.sleep(1)
print("D. B. Cooper takes the other")
time.sleep(1)
print("Your First officer (Co pilot) has the third one...")
time.sleep(1)
if option5 in ("1","one","One.","one.","One"): print("But gives it to you, and salutes you")
else:  time.sleep(1),print("You crash and die lol"), time.sleep(1),print("MAYBE if you befreinded him it wouldnt end here"), time.sleep(100000)
time.sleep(1)
print("He tells you to go without him, with hesitation you go...")

time.sleep(0.5)
print("Your in the air...")
time.sleep(0.2)
print("You deploy your parachute")
time.sleep(0.5)
print("And make it safley")
time.sleep(1)
print("On the other hand....")
time.sleep(2)
print("Your First officer (Co-pilot) did not make it...")
time.sleep(1)
print("He died a hero....")
time.sleep(1)
print("You go on to live life as one of the richest men after making something called cocomelon")
time.sleep(1)
print("Only two people made it to Texas that day...")
time.sleep(1)
print("Since your still in air")
print("MEANING TWO PEOPLE HAD THE OPPORTUNITY TO GO TO JURASSIC PARK")
time.sleep(1)
option1 = input("Do you want to continue and play PT2 right here? : ")
print("Or you could play it on the other repls.")
if option1 in ("Yes","Yes.","yes","yes.","y","Y","Y.","y.","Ya.","Ya","ya","ya.","Sure.","sure.","sure","sure."): time.sleep(1),print("Okay, loading..")
else: time.sleep(1),print("Okay.."),time.sleep(1),print("If you want to get back to this option you need to restart the whole repl."),time.sleep(1),print("Then I recomend going to the repl"),time.sleep(100000)
time.sleep(4)
print("\n"*53)
print("Fly an airplane! PT.2")
print("\n"*4)
time.sleep(1)
print("You now have the parachute.")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: To use it")
time.sleep(1)
print("2: Not use it")
time.sleep(1)
option1 = input("Which do you choose?  : ")
if option1 in ("2","Two","two.","Two.","two"): time.sleep(1), print("You didnt use it..")
else:time.sleep(1), print("KABOOOM!"), time.sleep(1), print("Someone had put in a C4 in the backpack"),time.sleep(1), print("which was ultimitly connected to the strap you just pulled"), print("You died!"),exit("Lol you suck")
print("")
time.sleep(1)
print("As your freefalling you notice Michael Jackson died and his parachute is loose...")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: Steal the parachute..")
print("2: Keep freefalling")
option2 = input("Which do you choose? : ")
if option2 in ("1","One.","one","one.","One"):time.sleep(1), print("You stole Michael Jacksons parachute."), time.sleep(1),print("As you look up ColoredHue is attacking you with a fried chicken.."),time.sleep(1),print("He claims that he needed to...")
else: time.sleep(1), print("You plumeted to the ground in a matter of seconds and died"),time.sleep(1), print("Your funeral was held at Jurassic park.."),exit()
print("")
print("ColoredHue is about to slice your parachute")
time.sleep(1)
print("You have two options : ")
time.sleep(1)
print("1: Get your glock.")
time.sleep(1)
print("2: Hit him.")
option3 = input("What will you do? : ")
if option3 in ("1","One","One.","one","one."):time.sleep(1), print("You dont have a glock.."), time.sleep(1), print("You have one option..."), time.sleep(1), print("1: Hit him back."), 

print("After you hit him his own chicken wing sliced his parachute leading to ColoredHue's death"),time.sleep(1),print("His funeral was held at wendys..")  
print("")
time.sleep(1)

print("You hit him again somehow even after he died")

print("Later you realized something sinister was going on.....")
time.sleep(1)
print("You remember that you said Your mom to eric and he never forgave you ")
time.sleep(1)
print("Idk what that has to do with this tho")
time.sleep(1)
print("\n"*25)
import os
import time

print("Part three of Fly an airplane, shoutout to ColoredHue, aboutabout, and IceMasterEric for *agreeing* (Kinda) to being in this series. Go try out their games! ")
print("Answer this question wisely, because if you want to come back you need to do all of PT1 again...")
time.sleep(2)
option12 = input("Would you like to continue to part 3? : ")
if option12 in ("One","one","Yes.","yes.","ye.","Ye.","Yes","yes","ye","Ye","Yeah","yeah","yeah.","Yeah.","y","Y","Sure.","Sure","sure","sure."):time.sleep(1), print("Proceeding to PT3")
else: time.sleep(1),print("Okay, permanently pausing game for this run.."),time.sleep(1000000)
print("")
time.sleep(1)
print("* Warning* Grammatical errors will lead to big mistakes!")
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(0.5)
print("")
time.sleep(1)
print("\n"*23)
print("You are now in the air, approching Jurassic park and Wendys.")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: Land in Jurrasic park.")
time.sleep(1)
print("2: Land at Wendys.")
time.sleep(1)
option1 = input("Which do you choose?  : ")
if option1 in ("1","One","One.","one","one."): time.sleep(1), print("You land at the Jurrasic park..")
else:time.sleep(1), print("You land at Wendys..."),time.sleep(1),print("Since the manager died Wendys has been going insane latley..."),time.sleep(1),print("You see something move with the corner of your eye..."),time.sleep(1), print("ITS WENDY!!"),time.sleep(1),print("She eats you and you die"),print("Your funeral was held in Wendys stomach.."),time.sleep(100000000)
time.sleep(1)
print("")
print("You see a Dinosour chasing you!")
time.sleep(1)
print("You have two options!")
time.sleep(1)
print("1: RUN!!")
print("2: Stand there...")
option2 = input("What do you do? : ")
if option2 in ("1","one","one.","One.","One"): 
  time.sleep(1), print("You ran.")
else:time.sleep(1), print("The dinosour, wasnt a dinosour and was just a turtle.."),time.sleep(1), print("You walked away..")
print("")
time.sleep(1)
print("You made it to this huge building.. ")
time.sleep(1)
print("You have two options.. ")
time.sleep(1)
print("1: Go in it..")
time.sleep(1)
print("2: Dont go in it..")
time.sleep(1)
option4 = input("What do you choose? : ")
if option4 in ("1","one","one.","One.","One"): time.sleep(1), print("You went in it..")
else:time.sleep(1), print("Some giant animal named bot ate you after you stood there for a while.."),time.sleep(1000000000)
print("")
time.sleep(1)
print("As your going up the stairs you see a room, the managers room.... and you went in it...")
time.sleep(1)
print("Theres someone thats sitting in the chair...")
time.sleep(1)
print("As you think to yourself weird, didnt the manager d--")
time.sleep(0.1)
print("YOU GET KIDNAPPED!")
import time
import os
import sys
option102 = input("Would you like to play PT4 right here? : ")
if option102 in ("One","one","Yes.","yes.","ye.","Ye.","Yes","yes","ye","Ye","Yeah","yeah","yeah.","Yeah.","y","Y","Sure.","Sure","sure","sure."): print("Proceeding to PT4")
else: time.sleep(1),print("Okay, permanently pausing game for this run.."),time.sleep(1000000)
print("\n"*79)
print("Welcome to PT4 of fly an airplane, a continuation of PT3, PT2, and PT1, this PT is longer and harder, good luck!")
print("Btw only use Yes, and No.")
time.sleep(2)
print("\n"*4)
time.sleep(1)
print("You are kidnapped!")
time.sleep(1)
print("The kidnappers tell you to remember a code")
time.sleep(1)
print("They tell you the code is : 1, 2, 8, 10, 16")
time.sleep(1)
print("You have 4 seconds to memorize these.. ")
time.sleep(1)
print("\n"*1054)
time.sleep(1)
option1 = input("What was the first number of the code? : ")
if option1 in ("1","one","One.","one.","One"): time.sleep(1),print("Correct!, you get to move on..")
else: time.sleep(1), print(":)"),time.sleep(1),print("That was the wrong answer :)"),time.sleep(1),print("He made you smell dog poop and you instantly died!"),time.sleep(1), print("Your funeral was held at wendys.."),time.sleep(1), print("When you went to wendys it was out of business..."),time.sleep(1),print("Your funeral was held at Pokémon Ultimates"),time.sleep(100000000000)
print("")
time.sleep(1)
option2 = input("What was the second number of the code? : ")
if option2 in ("2","two","two.","Two","Two."): time.sleep(1), print("Correct!"),time.sleep(1),print("You get to move on...")
else: time.sleep(1), print("Wrong, he shot you and you died.."),time.sleep(1), print("Your funeral was held at Jurassic park."),time.sleep(100000000000000)
print("")
option5 = input("What was the third digit? : ")
if option5 in ("8","Eight","eight","Eight.","eight."):print("Correct!")
else: time.sleep(1),print("He shot you and you died..."),time.sleep(1), print("R.I.P"),time.sleep(1),print("Your funeral was held at McDonalds"), time.sleep(1000000)
print("Two more times!")
print("")
option6 = input("What was the fourth number? :")
if option6 in ("10","Ten.","Ten","ten","ten."): time.sleep(1),print("Correct!"), print("ONE LAST ONE!")
else:time.sleep(1), print("Your funeral was held at ur moms house"),time.sleep(100000)
print("")
print("")
option7 = input("WHAT WAS THE LAST ONE?!?! : ")
if option7 in ("16","Sixteen","Sixteen.","sixteen.","sixteen"): print("You get to move on..")
else: time.sleep(1),print("You didnt get to live another day, and you stayed in that room for the rest of your life..."), time.sleep(10000000)

time.sleep(1)
print("You get realesed")
print("")
time.sleep(1)
print("You are now in the managers room..")
print("The man in the chair is wearing a dream mask, so you don't get to see his face..")
time.sleep(1)
print("But why?")
time.sleep(1)
print("He claims to be the new owner...")
time.sleep(1)
print("While turning around he attempts to kill you...")
time.sleep(1)
print("But you dodge it..")
time.sleep(1)
print("He asks you about your career..")
time.sleep(1)
option8 = input("What is your career? : ")
if option8 in ("Pilot","pilot","pilot.","Pilot."): time.sleep(1), print("Hm...")
else:time.sleep(1), print("He already knows you career and kills you!"),time.sleep(1), print("Because you got it wrong"),print("Your funeral was held at Talking Bens house.."),time.sleep(10000000)
print("He offers you to fly a plane, and you can be the pilot.")
time.sleep(1)
option9 = input("Do you accept (Say yes, fr): ")
if option9 in ("Yes","yes","yes.","Yes."): time.sleep(1),print("You get in the plane")
else:time.sleep(1), print("You go anyway..")
print("")
time.sleep(1)
print("You are now in the cockpit..")
time.sleep(1)
print("You have two options..")
print("1: Take off..")
time.sleep(1)
print("2: Take off..")
time.sleep(1)
print("You took off")
time.sleep(1)
print("This all feels familiar..")
time.sleep(1)
print("As if you've flown with this person")
time.sleep(1)
print("As your thinking..")
time.sleep(1)
print("The plane plummetes below")
time.sleep(1)
print("The man is slowly dying and on the floor..")
time.sleep(1)
print("The man's mask falls off and...")
time.sleep(1)
print("he's ....")
time.sleep(1)
print("ERIC?!?!?")
time.sleep(1)
print("Eric: Yes, it's me...")
time.sleep(1)
print("Eric: From the time we met I hated you..")
time.sleep(1)
print("Eric: Remember the booby trap in the parachute?")
time.sleep(1)
print("Eric: That wasn't a coincidence, THAT WAS ME")
time.sleep(1)
print("Eric: Remember ColoredHue attacking you?")
time.sleep(1)
print("Eric: THAT WAS ALSO ME.")
time.sleep(1)
print("Eric: I WAS PLANNING TO REVIVE-")
time.sleep(1)
print("You shot the man and he died...")
time.sleep(1)
print("You go back to your house and think about what he said...")
time.sleep(1)
print("You think..")
time.sleep(1)
print("And think..")
time.sleep(1)
print("And come to a conclusion..")
time.sleep(1) 
print("About-")
time.sleep(1)
print("\n"*6)
option10005 = input("Do you want to continue to PT5? : ")
if option10005 in ("Yes.","yes.","ye.","Ye.","Yes","yes","ye","Ye","Yeah","yeah","yeah.","Yeah.","y","Y","Sure.","Sure","sure","sure."): time.sleep(1),print("Continuing")
else: print("Inf stopping.."), time.sleep(10000000)

import os
import time
print("Hello and welcome to PT5!")
time.sleep(1)

print("\n"*7)
time.sleep(1)
print("You came to a conclusion but you forgor it 💀💀💀")
time.sleep(1)
print("But you belive something fishy was going on")
time.sleep(1)
print("Because Eric said something about reviving someone before he died..")
time.sleep(1)
print("But who could it be?")
time.sleep(1)
print("So many people died that I dont even know who it could be...")
time.sleep(1)
print("")
print("While your having your panic you realize that your in the middle of a jungle...")
time.sleep(1)
print("Your only chance of survival is to make it back to Jurassic park..")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: Go into the forest.")
time.sleep(1)
print("2: Stay there and look for supplys..")
time.sleep(1)
option109 = input("What do you choose? : ")
if option109 in ("One","1","One.","one.","one"): time.sleep(1),print("You went into the forest..."),print("Wendys came and killed you after being loose.."),time.sleep(1),print("You kinda cant really have a funeral.."),time.sleep(1),print("L"),time.sleep(100000000)
else: time.sleep(1),print("You looked for supplys..")
time.sleep(1)
print("You found a knife..")
time.sleep(1)
print("And a very limited amount of food..")
time.sleep(1)
print("You have one option..")
time.sleep(1)
print("1: Go into the forest.")
time.sleep(1)
input("What do you choose? : ")
print("")
time.sleep(1)
print("Welp, anyway you went in the forest..")
time.sleep(1)
print("You felt tired...")
time.sleep(1)
print("And hungry..")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: EAT!!!")
time.sleep(1)
print("2: Sleep..")
print("Science class would come in handy..")
time.sleep(1)
option1010 = input("What do you choose? : ")
if option1010 in ("One","1","One.","one.","one"): time.sleep(1),print("You ate"),time.sleep(1)
else: time.sleep(1), print("You slept.."), time.sleep(2), print("While you were sleeping.."),time.sleep(1),print("Some critter ate your toes off.."),time.sleep(1), print("Resulting in bloodloss.."),print("R.I.P"),time.sleep(1000000000)
print("\n"*2)
time.sleep(1)
print("You kept walking after that...")
time.sleep(2.5)
print("You finally made it to jurassic park..")
time.sleep(1)
print("You decide to go to the managars room.")
time.sleep(1)
print("")
time.sleep(1)
print("Its locked!")
print("You have two options..")
time.sleep(1)
print("1: Use your knife to attempt to picklock..")
time.sleep(1)
print("2: Nothing.")
time.sleep(1)
option1011 = input("What do you choose? : ")
if option1011 in ("One","1","One.","one.","one"): time.sleep(1), print("Your knife broke like glass..")
else: time.sleep(1), print("While you were doing nothing.."),time.sleep(1), print("Some dinosour ate you!"), time.sleep(1000000000000)
print("")
time.sleep(1)
print("There was a key inside the knife!")
time.sleep(1)
print("You got inside....")
time.sleep(1)
print("Once you got inside you saw...")
time.sleep(1)
print("COLOREDHUE?!?!")
time.sleep(1)
print("wait...")
time.sleep(1)
print("COLOREDHUE INSIDE A HUGE JAR?!?!?!")
time.sleep(1)
print("There was a big red button..")
time.sleep(1)
print("Your favorite type of button....")
time.sleep(1)
print("You have two options..")
time.sleep(1)
print("1: press")
time.sleep(1)
print("2: not press :(")
option99 = input("Which do you pick? : ")
if option99 in ("1","one","one.","One.","One"): time.sleep(1),print("You pressed it...")
else: time.sleep(1),print("Not pressing it alerted the gaurds.."),time.sleep(1), print("Because Eric made it like that... Eric new that if you saw a red button you'd try to act smart and not press it..."),time.sleep(100000)
print("ColoredHue got released...")
time.sleep(1)
print("But he isnt ColoredHue..")
time.sleep(1)
print("He looks like a zombie..")
time.sleep(1)
print("The man lunges at you in an attempt to bite you..")
time.sleep(1)
print("But instantly your key turned into a cheese slaying cyber sword gun knife super laser weapon..")
time.sleep(1)
print("You hit him and he passed out lol...")
time.sleep(1)
print("THAT MEANS WENDYS IS BACK TO BUSINESS...")
time.sleep(1)
print("Meaning that you can get burgers..and fries...and chicki nugies")
time.sleep(1)
print("Anyway...")
time.sleep(1)
print("You hit him, and the gaurds were notified")
time.sleep(1)
print("They came in with guns...")
time.sleep(1)
print("But then their cheese slaying cyber sword gun knife super laser weopon turned into an AK-47")
time.sleep(1)
print("But it shot bubbles..")
time.sleep(1)
print("\n"*23)
print("PT6 coming out soon!")
time.sleep(1.5)
clear()
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)

time.sleep(1)
print("")
print("Part 6 coming OUT hahahahahahah lol")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("")
time.sleep(1)
print("Top 15 comments are getting a place here!!")
print("Alpharumeric: GG ez")

time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("Love you IcemasterEric")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("Zygrade is champ")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
time.sleep(1)

time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("ColoredHue is a legend")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("PT 6 COMING OUT SOON!!!")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
time.sleep(0.2)
print("")
print("Get a spot here by typing in chat a quote")
time.sleep(0.5)
print("Only the top 15 are here")
print("")
print("Alpharumeric: GG ez")
